apiVersion: v1
kind: Service
metadata:
  labels:
    role: client
  name: elasticsearch
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch
    role: client
  type: LoadBalancer
